config/routes.rb
Rails.application.routes.draw do

   get 'realimages/index'
   get 'realimages/search_record'
 
  root 'realimages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
end

app/controllers/realimages_controller.rb
class RealimagesController < ApplicationController
  before_action :set_realimage, only: [:show, :edit, :update, :destroy]
  require 'url_parse'
  # GET /realimages
  # GET /realimages.json
  def index
   # @realimages = Realimage.all
  end

  # GET /realimages/1
  # GET /realimages/1.json
  def show
  end
   
  # GET /realimages/new
  def new
    @realimage = Realimage.new
  end

  # GET /realimages/1/edit
  def edit
  end
  
  def search_record  
   @search_record = ::UrlParse.new.get_json_data(params[:search_name])
    render :partial => 'search_record'
  end

  # POST /realimages
  # POST /realimages.json
  def create
  end

  # PATCH/PUT /realimages/1
  # PATCH/PUT /realimages/1.json
  def update
  end

  # DELETE /realimages/1
  # DELETE /realimages/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realimage
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realimage_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/realimages_helper.rb
module RealimagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/realimages/_form.html.erb
<%= form_for(@realimage) do |f| %>
  <% if @realimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@realimage.errors.count, "error") %> prohibited this realimage from being saved:</h2>

      <ul>
      <% @realimage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/realimages/_search_record.html.erb
 <div class="container">
 <%if @search_record.present? %>
  <h1><%= @search_record['name']%></h1>
  <div class="row">
 <% key_vlu = @search_record.keys[3]%>
  <% @search_record[key_vlu].each do |value|  %>
    <div class="col-sm-3" >
      <p>Movies: <%= value["name"]%></p>
      <p>Role: <%= value["role"]%></p>
    </div>
    </br>
    <div class="col-sm-3" >
      <p>Movies: <%= value["name"]%></p>
      <p>Role: <%= value["role"]%></p>
    </div>
    </br>
    <div class="col-sm-3" >
      <p>Movies: <%= value["name"]%></p>
      <p>Role: <%= value["role"]%></p>
    </div>
    </br>
    <div class="col-sm-3" >
      <p>Movies: <%= value["name"]%></p>
      <p>Role: <%= value["role"]%></p>
    </div>
    </br>
    <%end%>
  </div>
  <%else%>
  <div class="col-sm-12" >
     <p>  No Record Available </p>
    </div>
  <%end%>
</div>
</div>

app/views/realimages/edit.html.erb
<h1>Editing Realimage</h1>

<%= render 'form' %>

<%= link_to 'Show', @realimage %> |
<%= link_to 'Back', realimages_path %>

app/views/realimages/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Realimages</h1>
<table>
  <thead>
    <tr>
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" id="addressSearch" type="button">Go!</button>
            </span>
          </div>
        </div>
        </div>
    </tr>
   </thead>
  <tbody>
   <div id="record_list">
   </div>
  </tbody>
</table>
<br>

<script>
$('#addressSearch').click(function () {
var name = $('input:text').val();
if(name == ""){
    alert("Please enter the valid text")
}
 $.ajax({
  url: "realimages/search_record?search_name=" + name,
        type: 'GET',
        success: function(response){   
          $('#record_list').html(response)
        }

    });
});
</script>

app/views/realimages/new.html.erb
<h1>New Realimage</h1>

<%= render 'form' %>

<%= link_to 'Back', realimages_path %>

app/views/realimages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_realimage_path(@realimage) %> |
<%= link_to 'Back', realimages_path %>